### ISSUE TITLE
Can't use your component

### ISSUE THREAD

**Issue by rizafahmi** [norsez/BDDynamicGridViewController#2]
Your component looks promising. But how can I use it with generic UIView on my own view controller? Your example doesn't have any xib file, I'm confuse. Newbie here :)

**Comment by norsez** [comment]
Interface builder can be tricky to use as Apple has no real documentation for it. 

See http://cl.ly/image/3P3I3g2r3E1Y 

See how I edit `Custom class` to be the name of this component. Since this class extends the UIView which is what the object in the XIB is, this should work. I haven't tested it though. If it doesn't, you can always do what my example does, i.e. build the component programmatically, which gives you more freedom later on. 

Good luck.
