### ISSUE TITLE
Layout subview is a consistent way

### ISSUE THREAD

**Issue by HeshamMegid** [norsez/BDDynamicGridViewController#7]
I'm trying to implement infinite scrolling using your control. I'm handling when the grid views hits the bottom, then I load new data and reload.

The problem is, when I reload the grid view, the views that where already there get a different layout/ordering. 

So my question is, how can I add new data to the grid view while maintaing the layout of the views currently displayed?

**Comment by norsez** [comment]
Hi @HeshamMegid ,

Sorry for late reply. Maintaining the layout is possible with -reloadDataWithGridPattern:. 

The -reloadData re-layouts everything automatically, and the layout is different every time. But I understand it messes up your infinite scrolling. 

Instead go with -reloadDataWithGridPattern:. With this method, you need to provide a static layout pattern when you call, say @[@2,@3,@1], to the method. The grid view controller will layout so that there are 2 views on the first row, 3 on the second, 1 on the third, 2 on the fourth, 3 on the fifth, and so on. (There's no limit to the number of items in the pattern, this is only an example.) This should keep your layout consistent every time you load new data. 

Hope it helps.

n

**Comment by HeshamMegid** [comment]
It's working fine now. Thanks for your explanation :)
